server:
  port: 9000
spring:
  application:
    name: native-jpa
  jpa:
    default:
      compile-time-hibernate-proxies: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        bytecode:
          provider: bytebuddy
    open-in-view: false
logging:
  level:
    root: info
    sql: trace