name: Native Image

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-native:
    name: 'native-demo Build Native Image ${{ matrix.platform }}'
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: 'ubuntu-latest'
            platform: 'linux-amd64'
    runs-on: ${{matrix.os}}
    permissions:
      contents: write
    steps:
      - name: linux packages
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      - name: Checkout the repository
        uses: actions/checkout@v6

      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'liberica'
          java-version: '21'
          java-package: 'jdk'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        shell: bash
        run: |
          mvn clean package
          java -agentlib:native-image-agent=config-output-dir=${project.basedir}/src/main/resources/META-INF/native-image -jar ./target/native-jpa-1.0.0-SNAPSHOT.jar
          mvn -Pnative native:compile-no-fork
          ls target
          ./target/native-jpa
          sleep 60
          mvn clean